### ISSUE TITLE
Error on PowerShell 5.1.14393.1066

### ISSUE THREAD

**Issue by DarwinJS** [cloudbase/powershell-yaml#9]
On windows 10, with the following $psversiontable output:

Name                           Value
----                           -----
PSVersion                      5.1.14393.1066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

I am getting the following error:
```
ErrorRecord                 : Exception calling "Load" with "1" argument(s): "(Line: 7, Col: 32, Idx: 143) - (Line: 7, 
                              Col: 33, Idx: 144): While parsing a block mapping, did not find expected key."
WasThrownFromThrowStatement : False
Message                     : Exception calling "Load" with "1" argument(s): "(Line: 7, Col: 32, Idx: 143) - (Line: 7, 
                              Col: 33, Idx: 144): While parsing a block mapping, did not find expected key."
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.Management.Automation.MethodInvocationException: Exception calling "Load" with 
                              "1" argument(s): "(Line: 7, Col: 32, Idx: 143) - (Line: 7, Col: 33, Idx: 144): While 
                              parsing a block mapping, did not find expected key." ---> 
                              YamlDotNet.Core.SemanticErrorException: (Line: 7, Col: 32, Idx: 143) - (Line: 7, Col: 
                              33, Idx: 144): While parsing a block mapping, did not find expected key.
                                 at YamlDotNet.Core.Parser.ParseBlockMappingKey(Boolean isFirst) in 
                              c:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 709
                                 at YamlDotNet.Core.Parser.MoveNext() in 
                              c:\projects\yamldotnet\YamlDotNet\Core\Parser.cs:line 114
                                 at YamlDotNet.Core.EventReader.Allow[T]() in 
                              c:\projects\yamldotnet\YamlDotNet\Core\EventReader.cs:line 110
                                 at YamlDotNet.Core.EventReader.Expect[T]() in 
                              c:\projects\yamldotnet\YamlDotNet\Core\EventReader.cs:line 67
                                 at YamlDotNet.RepresentationModel.YamlScalarNode..ctor(EventReader events, 
                              DocumentLoadingState state) in 
                              c:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlScalarNode.cs:line 57
                                 at YamlDotNet.RepresentationModel.YamlNode.ParseNode(EventReader events, 
                              DocumentLoadingState state) in 
                              c:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlNode.cs:line 84
                                 at YamlDotNet.RepresentationModel.YamlMappingNode..ctor(EventReader events, 
                              DocumentLoadingState state) in 
                              c:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlMappingNode.cs:line 71
                                 at YamlDotNet.RepresentationModel.YamlNode.ParseNode(EventReader events, 
                              DocumentLoadingState state) in 
                              c:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlNode.cs:line 94
                                 at YamlDotNet.RepresentationModel.YamlDocument..ctor(EventReader events) in 
                              c:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlDocument.cs:line 72
                                 at YamlDotNet.RepresentationModel.YamlStream.Load(EventReader reader) in 
                              c:\projects\yamldotnet\YamlDotNet\RepresentationModel\YamlStream.cs:line 104
                                 at CallSite.Target(Closure , CallSite , Object , TextReader )
                                 --- End of inner exception stack trace ---
                                 at 
                              System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                              funcContext, Exception exception)
                                 at 
                              System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
                              frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(Interp
                              retedFrame frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
                              dollarUnderbar, Object inputToProcess)
                                 at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetSite                  : System.Collections.ObjectModel.Collection`1[System.Management.Automation.PSObject] 
                              Invoke(System.Collections.IEnumerable)
StackTrace                  :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                                 at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, 
                              Exception& exceptionThrown, ExecutionOptions options)
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087
```

**Comment by DarwinJS** [comment]
Sorry some sort of file or data format problem
